#pragma once

// On Windows this fork is built as a static library (qtermwidget_win), so
// there is nothing to export. On Linux it is built as a shared library with
// -fvisibility=hidden, so QTERMWIDGET_EXPORT must expand to a default
// visibility attribute (mirroring the header generated by generate_export_header).
// Note: Q_DECL_EXPORT is avoided because some Qt builds define it as
// visibility("protected"), which breaks linking against the executable.
#if defined(Q_OS_WIN)
#define QTERMWIDGET_EXPORT
#define QTERMWIDGET_NO_EXPORT
#define QTERMWIDGET_DEPRECATED
#else
#define QTERMWIDGET_EXPORT __attribute__((visibility("default")))
#define QTERMWIDGET_NO_EXPORT __attribute__((visibility("hidden")))
#define QTERMWIDGET_DEPRECATED __attribute__((deprecated))
#endif